version: '3.8'

services:
  frontend:
    build: ../frontend
    volumes:
      - static:/app/result_build/

  backend:
    build: ../backend
    volumes:
      - media:/app/media
      - static:/static
    environment:
      - DEBUG=True
      - SECRET_KEY=test-key-123
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - frontend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/var/html/media/
    depends_on:
      - backend


volumes:
  static:
  media: